version: '3'

services:

 mariadb:
  container_name: mariadb
  networks:
   - inception
  build:
   context: requirements/mariadb
  env_file: .env
  volumes:
   - /home/hedubois/data/mariadb:/var/lib/mysql
  restart: unless-stopped
  expose:
   - "3306"

 wordpress:
  container_name: wordpress
  hostname: wordpress
  networks:
    - inception
  build:
   context: requirements/wordpress
  env_file: .env
  volumes:
   - /home/hedubois/data/wordpress:/var/www/html
  depends_on:
   - mariadb
  restart: on-failure
  expose:
   - "9000"

 nginx:
  container_name: nginx
  hostname: hedubois.42.fr
  networks:
   - inception
  build: 
   context: requirements/nginx
  env_file: .env
  volumes:
   - /home/hedubois/data/wordpress:/var/www/html
  depends_on:
   - wordpress
   - mariadb
  restart: on-failure
  ports:
   - "443:443"
  expose: 
   - "443"

volumes:

 mariadb:
  driver: local
  driver_opts:
   type: none
   o: bind
   device: '/home/hedubois/data/mariadb'
 
 wordpress:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/hedubois/data/wordpress'

networks:
 inception:
  driver: bridge
